name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run basic tests
      run: node --experimental-vm-modules node_modules/jest/bin/jest.js __tests__/basic.test.js
    
    - name: Run server health check test
      run: node --experimental-vm-modules node_modules/jest/bin/jest.js __tests__/server.test.js
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        NOVITA_API_KEY: ${{ secrets.NOVITA_API_KEY }}
        CORS_ORIGIN: '*'
    
    - name: Verify server starts
      run: |
        npm start &
        SERVER_PID=$!
        sleep 5
        kill $SERVER_PID
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        NOVITA_API_KEY: ${{ secrets.NOVITA_API_KEY }}
        CORS_ORIGIN: '*'

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        fail_ci_if_error: false 