name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run basic tests
      run: node --experimental-vm-modules node_modules/jest/bin/jest.js __tests__/basic.test.js
    
    - name: Create .env file for testing
      run: |
        echo "AWS_REGION=us-east-1" > .env
        echo "AWS_BUCKET_NAME=test-bucket" >> .env
        echo "NOVITA_API_KEY=test-key" >> .env
        echo "CORS_ORIGIN=*" >> .env
    
    - name: Run server health check test
      run: node --experimental-vm-modules node_modules/jest/bin/jest.js __tests__/server.test.js
      env:
        AWS_REGION: 'us-east-1'
        AWS_BUCKET_NAME: 'test-bucket'
        NOVITA_API_KEY: 'test-key'
        CORS_ORIGIN: '*'
    
    - name: Verify server starts
      run: |
        npm start &
        SERVER_PID=$!
        sleep 5
        kill $SERVER_PID || true
      env:
        AWS_REGION: 'us-east-1'
        AWS_BUCKET_NAME: 'test-bucket'
        NOVITA_API_KEY: 'test-key'
        CORS_ORIGIN: '*'

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        fail_ci_if_error: false 